export const typeMap: Record<string, { icon: string; color: string }> = {
  bug: { icon: "/images/typeIcon/Bug_icon_SwSh.png", color: "#A8B820" },
  dark: { icon: "/images/typeIcon/Dark_icon_SwSh.png", color: "#705848" },
  dragon: { icon: "/images/typeIcon/Dragon_icon_SwSh.png", color: "#7038F8" },
  electric: { icon: "/images/typeIcon/Electric_icon_SwSh.png", color: "#F8D030" },
  fairy: { icon: "/images/typeIcon/Fairy_icon_SwSh.png", color: "#EE99AC" },
  fighting: { icon: "/images/typeIcon/Fighting_icon_SwSh.png", color: "#C03028" },
  fire: { icon: "/images/typeIcon/Fire_icon_SwSh.png", color: "#F08030" },
  flying: { icon: "/images/typeIcon/Flying_icon_SwSh.png", color: "#A890F0" },
  ghost: { icon: "/images/typeIcon/Ghost_icon_SwSh.png", color: "#705898" },
  grass: { icon: "/images/typeIcon/Grass_icon_SwSh.png", color: "#78C850" },
  ground: { icon: "/images/typeIcon/Ground_icon_SwSh.png", color: "#E0C068" },
  ice: { icon: "/images/typeIcon/Ice_icon_SwSh.png", color: "#98D8D8" },
  normal: { icon: "/images/typeIcon/Normal_icon_SwSh.png", color: "#A8A878" },
  poison: { icon: "/images/typeIcon/Poison_icon_SwSh.png", color: "#A040A0" },
  psychic: { icon: "/images/typeIcon/Psychic_icon_SwSh.png", color: "#F85888" },
  rock: { icon: "/images/typeIcon/Rock_icon_SwSh.png", color: "#B8A038" },
  steel: { icon: "/images/typeIcon/Steel_icon_SwSh.png", color: "#B8B8D0" },
  water: { icon: "/images/typeIcon/Water_icon_SwSh.png", color: "#6890F0" },
};
